[package]
name = "belog"
version = "0.1.0"
authors = ["Justus K. <justus.k@protonmail.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4.8", features = ["std"] }
colored = { version = "1.9.0", optional = true }
